spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zhihu_api?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# 配置Spring MVC静态资源
  mvc:
    static-path-pattern: /static/**

  # Redis 配置
  data:
    redis:
      # Redis 服务器地址
      host: 127.0.0.1
      # Redis 服务器连接端口
      port: 6379
      # Redis 数据库索引(默认为 0)
      database: 0
      # Redis 服务器连接密码(默认为空)
      password:
      # 连接超时时间(毫秒)
      timeout: 5000
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 10
          # 连接池中的最大空闲连接
          max-idle: 20
          # 连接池最大连接数(使用负值表示没有限制)
          max-active: 100
          # 连接池最大阻塞等待时间(使用负值表示没有限制)
          max-wait: -1

  # Redis 缓存配置
  cache:
    # 启用缓存
    type: redis
    # 缓存过期时间(秒)
    redis:
      time-to-live: 3600

# 配置Mybatis
mybatis-plus:
  #  指定相应接口对应的xml文件所在目录
  mapper-locations: classpath:mapper/*.xml
  #  实体类所在包
  type-aliases-package: com.rbc.zhihu.api.entity
  configuration:
    # mybatis开启驼峰式命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值

# 应用服务端口
server:
  port: 8080



rbc:
  sms:
    ccp:
      serveIP: app.cloopen.com
      port: 8883
      accountSId: 2c94811c8cd4da0a018f047871856ab5
      accountToken: b84ebec7313344378e8e3f02e7bd6616
      appID: 2c94811c8cd4da0a018f047873166abc
      templateId: 1 # 短信模板ID


fileTemp:
  url: "C:\\Users\\DingYihang\\Pictures"